### ISSUE TITLE
Confusing message on appending to non-initialized collection

### ISSUE THREAD

**Issue by Szer** [jet/equinox#122]
Trying to append to non-initialized collection returns `AppendResult.Conflict(0, [||])`  which tells us that `there are conflict on appending event with index=0 and there are no conflicts` :)

We should add another `AppendResult` for that case.

**Comment by bartelink** [comment]
Can you supply a repro (ideally as a failing test) please ?

This general functionality is covered by the tests in the vicinity of  https://github.com/jet/equinox/blob/49eb3a141eba51f656180b42a26aa43cf169c349/tests/Equinox.Cosmos.Integration/CosmosCoreIntegration.fs#L173 see e.g. L183

**Comment by bartelink** [comment]
Closing for age (DM says it was a false alarm)
