### ISSUE TITLE
rename DeprecatedRawName ?

### ISSUE THREAD

**Issue by bartelink** [jet/equinox#147]
The name [`DeprecatedRawName`](https://github.com/jet/equinox/blob/ee7d4e4ca2a32612a9defdf496259b891f3bb1e5/src/Equinox/Stream.fs#L46) was chosen in haste; I was seeking to:
a) give a pejorative name to make people think before putting string concats composing a name into their app logic - `AggregateId` provides a clean way to compose a category name literal with an identifier in code
b) give a strong nudge to use `AggregateId` as it ensures that the out-of-the-box default separator used by EventStore (`"-"`) gets used which makes `$ec-` streams etc work
c) provides scope to map `AggregateId` to something appropriate for any new store

On reflection, while there's nothing wrong with the above opinionated stance, the reality is that plenty existing codebases already compose names in a variety of ways, and will pick a backend and stick with it.

So, for the final v2 release, I'm open to a name change if we can settle on one. Open to any thoughts...

**Comment by bartelink** [comment]
Ccing @ameier38 in case you can think of a better name than `StreamName`

**Comment by ameier38** [comment]
I like `StreamName` 👍

**Comment by bartelink** [comment]
Completed in #150
