### ISSUE TITLE
Script MsSql database creation for Equinox.SqlStreamStore.MsSql

### ISSUE THREAD

**Issue by bartelink** [jet/equinox#175]
In order to be able to validate correct functioning against Sql Server, there's a missing bit: there's no code/script in this repo that will establish a test database at present (the integration test and/or `eqx config` can do the DDL to create the schema - its purely the `CREATE DATABASE` bit that's missing)

- ~hack at the `docker-compose.yml` to create a known database~ 🙈 
- Script creation of a database and/or starting of a Sql Server Database of some form in docker, e.g. using https://github.com/HofmeisterAn/dotnet-testcontainers

(Holdover task from #168)

**Comment by enricosada** [comment]
i used this in some places, just `docker run` and a connection string to use it.
Can be inside the `compose` as needed

```fsharp
    //To create the database for testing:
    // docker run -e ACCEPT_EULA=Y -e SA_PASSWORD=Banana100 -p 1433:1433 --name sql1 microsoft/mssql-server-linux:2017-latest

    //connection to local database for testing
    let [<Literal>] ConnectionString = @"Data Source=localhost;Initial Catalog=master;Persist Security Info=True;User ID=sa;Password=Banana100"
```
