### ISSUE TITLE
AwaitTaskCorrect

### ISSUE THREAD

**Issue by edgarjrg** [jet/equinox#198]
Hi! Is there a nuget package with the `AwaitTaskCorrect` part?

https://github.com/jet/equinox/blob/74129903e85e01ce584b4449f629bf3e525515ea/src/Equinox.Core/Infrastructure.fs#L38

I've seen [other snippets](http://www.fssnip.net/7Rc/title/AsyncAwaitTaskCorrect) with the same-ish solution.

**Comment by bartelink** [comment]
Good question. Sadly, the answer is pretty much no.

The origin is: http://www.fssnip.net/7Rc/title/AsyncAwaitTaskCorrect - maybe @eiriktsarpalis has more info?

The closest library I know of in this space is https://github.com/rspeele/TaskBuilder.fs (which large aspects of likely to eventually make it into FSharp.Core)

(Obviously, it's not needed for using Equinox itself, as it exposes `Async<T>` where appropriate; the helper is intentionally `internal` and compiled into each module so as to avoid polluting namespaces and/or dependency graphs)

**Comment by eiriktsarpalis** [comment]
I'd recommend creating an issue in the F# repo. This should have been the default behaviour of `Async.AwaitTask` (considering that C# task awaiters do the same thing), however changing the current method is a breaking change.

**Comment by edgarjrg** [comment]
Thanks for your answer @bartelink, not sure how TaksBuilder would replace that simple snippet, but I'll take a deeper look to see if there are more advantages for using TaskBuilder over the snippet.

I followed your recommendation @eiriktsarpalis 👍
