### ISSUE TITLE
FSharp.Control.AsyncSeq error

### ISSUE THREAD

**Issue by fluxlife** [jet/equinox#218]
**.Net Version:** .Net Core 3.1
**OS:** Mac OS
**Packages:**
nuget Equinox.Core 2.0.0
nuget Equinox.SqlStreamStore 2.0.0
nuget Equinox.SqlStreamStore.MsSql 2.0.0
nuget FsCodec 2.0.2-alpha.0.8 alpha
nuget SQLStreamStore 1.2.0-beta.8
nuget SQLStreamStore.MsSql 1.2.0-beta.8

When trying to `Transact` on a stream I am getting this error:
```
Cause: System.AggregateException: One or more errors occurred. (Could not load file or assembly 'FSharp.Control.AsyncSeq, Version=2.0.21.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040))
 ---> System.IO.FileLoadException: Could not load file or assembly 'FSharp.Control.AsyncSeq, Version=2.0.21.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'FSharp.Control.AsyncSeq, Version=2.0.21.0, Culture=neutral, PublicKeyToken=null'
   at Equinox.SqlStreamStore.Read.loadForwardsFrom@220.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at Ply.TplPrimitives.TaskAwaiterMethods`1.Ply-TplPrimitives-IAwaiterMethods`2-GetResult(TaskAwaiter`1& awt)
   at Ply.TplPrimitives.TplAwaitable`4.GetNext()
   at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()


   --- End of inner exception stack trace ---
```

I also added `FSharp.Control.AsyncSeq` to my project to see if that would resolve any issues and it didn't appear to.

**Comment by bartelink** [comment]
Apologies for slow response - the ES, SSS and Cosmos plugins all depend on https://www.nuget.org/packages/Equinox.SqlStreamStore/3.0.0-alpha.3
AsyncSeq >= 2.0.23 - this suggests there is some assembly redirect in the mix that's causing a redirect to an incompatible version
In general, if specifying packages in paket, be careful not to overconstrain things, as they end up overriding the checks - e.g. the SQLStreamStore.*, Equinox.Core and Equinox.SqlStreamStore in the above are nice for completeness in this report but def should not be in the .dependencies file

**Comment by bartelink** [comment]
Also v 2.0.1 contains a critical bugfix for Equinox.SSS.MSSQL

**Comment by fluxlife** [comment]
Ah, will update to all the latest, check back, and close if necessary.  That's what I get for copying deps from another paket file.

**Comment by fluxlife** [comment]
nuget Equinox.Core >= 3.0.0-alpha.3
nuget Equinox.SqlStreamStore >= 3.0.0-alpha.3
nuget Equinox.SqlStreamStore.MsSql >= 3.0.0-alpha.3
nuget SQLStreamStore  >= 1.2.0-beta.8
nuget SQLStreamStore.MsSql >= 1.2.0-beta.8

This is the only way I have been able to get some constraints to work but I am still getting the error.

**Comment by bartelink** [comment]
Hm while @ylibrach is running 3.0.0, In general, I'd advise staying on 2.0.1 - it works fine on netcoreapp3.1 (and net461 FWIW)
What happens if you unpin all but `Equinox.SqlStreamStore.MsSql >= 3.0.0-alpha.3` ?
Can you share more of the `.dependencies` and/or whether the `.lock` file is showing AsyncSeq v .21 or .23 ?

**Comment by fluxlife** [comment]
Paket fails with:
```
 Conflict detected:
      - Dependencies file requested package Equinox.SqlStreamStore: >= 0
      - Equinox.SqlStreamStore.MsSql 3.0.0-alpha.3 requested package Equinox.SqlStreamStore: >= 3.0.0-alpha.3 (alpha)*
```

**Comment by bartelink** [comment]
Hm, its possible that the v3 alpha branch does not have full in sync SqlStreamStore dependencies, though its more likely that `Equinox.SqlStreamStore >= 0` means you have specified that but not opted into `prerelease`s in that context - for simplicity you're best off validating things using 2.0.1 across the board (and probably sticking with FsCodec.NewtonsoftJson to reduce the variables in play)

**Comment by fluxlife** [comment]
Deleting paket.lock, making suggested modifications to paket, and reinstalling/restoring everything seemed to fix this specific issue. Will close.

**Comment by bartelink** [comment]
cc @fnipo From looking around, it seems the confusion here stems from a mix of things
- v `3.0.0-alpha.3` uses AsyncSeq v `2.0.23` (required as Equinox.Cosmos uses the Cosmos V4 SDK which requires `IAsyncEnumerable`)
- v `1`/`2`.x all use `2.0.21`

=> For avoidance of doubt 1. Don't pin AsyncSeq 2. use `git clean`

@fluxlife A secondary confusion which probably landed you in this loop is the fact that there was a manual incomplete version of `Equinox.SqlStreamStore.MsSql` - a `2.0.1` was released, but no accompanying other packages

=> I'm releasing a `2.0.2` and unlisting `2.0.1` to reduce the likelihood of others running into similar issues
