### ISSUE TITLE
Change Feed Queation

### ISSUE THREAD

**Issue by mpaul31** [jet/equinox#220]
Hello

Is there any documentation or can you explain how retries are managed via cosmos change feed? i’m just trying to get a better understanding for the infrastructure pieces.

thanks!

**Comment by bartelink** [comment]
In general, such things live in Propulsion - the diagrams hopefully convey some of it. I'll try to summarize at a high level here:
1. Equinox reads/writes at stream level - the Transact loop manages two kinds of retries
   a) for infrastructure issues e.g. connectivity
   b) for concurrency conflicts (by re-running the decision in light of conflicting events)
2. Propulsion reads from the changefeed
   a) the checkpoints per consumer group live in the `aux` container
   b) the current lease assignments per running instance of the Projectors for a given consumer group in a Container also live in that `aux`
   c) if a handler invocation for a given stream fails, it's retained and retried
   d) the Scheduler feeds progress back to the reader, which periodically commits it (if one stream was continually failing, progress would not be marked past any events that have not yet been handled)

Whenever a projector is restarted, or the ChangeFeedProcessor reassigns a lease, the at least once delivery semantics take effect -- handlers will be re-invoked with events that may already have been attempted. For this reason, any writes should be managed in an idempotent manner.

Going to close this now but feel free to ask followup-questions if any arise
