### ISSUE TITLE
Cosmos: Dispose queries/results if releasing against Cosmos SDK V3 instead of V4

### ISSUE THREAD

**Issue by bartelink** [jet/equinox#225]
NOTE This does not apply to the present 2.x release series

The `Microsoft.Azure.Cosmos` APIset [introduces `IDisposable` on queries and responses](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1638) - the current `master`/`main` branch uses this 'V3' API and hence should be updated to ensure memory usage is correct and/or optimal.

I believe the `Azure.Cosmos` (aka V4) SDK makes this moot by exposing the features as `IAsyncEnumerable`. Thus, assuming we don't release an impl targeting V3 and instead leapfrog from SDK v2 to V4 via https://github.com/jet/equinox/pull/197 we can avoid needing any code changes.

**Comment by kirankumarkolli** [comment]
@bartelink IAsyncEnumerable is IAsyncDisposable. 

Usage pattern (await foreach) disposes underlying, is a convenience. Outside the that usage pattern its ideally expected to be disposed explictly.

**Comment by bartelink** [comment]
Thanks for clarifying.

The Equinox impl against V4 [preview3] in https://github.com/jet/equinox/pull/197 already uses the higher level `IAsyncEnumerable` interface. Assuming the next V4 preview ([with RU consumption fixes in 3.9.0 included too](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/616#issuecomment-629813295)), this issue will thus become moot (i.e. there wont be a non-alpha release of Equinox.Cosmos targeting `Microsoft.Azure.Cosmos` and/or working with the lower level APIs).
