### ISSUE TITLE
What are the pros and cons of EventStore vs Cosmos?

### ISSUE THREAD

**Issue by dharmaturtle** [jet/equinox#285]
As I see it:

EventStore pros:
* Simpler (than Cosmos)
* Built-in push-based projections
* Can be self-hosted
* Has an `$all` stream

Cosmos pros:
* Scales well
* Pay-for-what-you-use
* ...?

I'm pretty sure I'm missing some serious stuff. Is scale the primary reason why Jet-mart uses Cosmos?

**Comment by bartelink** [comment]
(I see this is closed, but for posterity...)

I'd say assessing such tradeoffs is best approached as a discussion on the DDD-CQRS-ES forum

While it's possible to enumerate some generalities, you're going to have a way better outcome if you consider such a comparison in the context of a real business problem taking into account the size of the company, diversity of clients, potential load, operating model etc.

On StackOverflow, this would be closed as 'product recommendations are not a good fit for out format' ;)
