### ISSUE TITLE
V2: Cosmos: Backport LogSink signature change

### ISSUE THREAD

**Issue by bartelink** [jet/equinox#290]
We need to make a V2 release of https://github.com/jet/equinox/commit/1d657f4ae1e0bbcfe4b0236640d6480ee2585fcc in order to preserve symmetry with it and Propulsion wrt the final custom tags signatures @deviousasti implemented

Any imminent release of V2 should also strongly consider solving #289

**Comment by deviousasti** [comment]
I'll take that up.

**Comment by bartelink** [comment]
@deviousasti I propose closing this on the basis that (given V3 is in common usage), the workaround is to upgrade to migrate from Equinox.Cosmos to [V3] Equinox.CosmosStore before doing instrumentation.
