### ISSUE TITLE
StreamNotFoundException when trying to add Events to a new Stream with EventStoreDb

### ISSUE THREAD

**Issue by keppelerj** [jet/equinox#370]
When trying to use Equinox EventStoreDb I encountered a StreamNotFoundException whenever I tried to add the first Event to a new Stream. (Strangely creating the first Event and thus creating the Stream worked via the AdminUI. Also appending to this Stream with my implementation worked fine after creating the first event via the AdminUI).

Since I'm pretty much new to Equinox my first guess was that I configured something wrong. So I tried to setup the "Backend Todo" dotnet template and figure it out myself. But here I encountered the exact same error.

Steps to reproduce:
1. Follow instructions of this: https://github.com/jet/equinox#store-data-in-eventstore
(Note that I did use 22.10.1-buster-slim instead of 21.10.0-buster-slim, but I figured this should actually be the correct version since Equinox.EventStore is using the Client for Version 22.0.0-preview https://github.com/jet/equinox/blob/master/src/Equinox.EventStore/Equinox.EventStore.fsproj#L23 )
2. Run a POST HTTP request against http://localhost:5000/todos with the following payload
`{
    "id": 0,
    "url": "string",
    "order": 0,
    "title": "string",
    "completed": false
}`

When I had a quick look at the code line where the Exception was thrown I saw that the wrong Exception got caught here.

Code line in EventStoreDb.fs where the Exception was thrown:
https://github.com/jet/equinox/blob/d5cc2c92028405900daeaaf5bac2bca7f077ebe3/src/Equinox.EventStoreDb/EventStoreDb.fs#L198

When I replaced this line with
`with :? StreamNotFoundException)`
it worked fine in the "Backend Todo" example.

Is it possible that the Exception signature here is simply no up to date with the latest EventStore version?
See: https://github.com/EventStore/EventStore-Client-Dotnet/blob/master/src/EventStore.Client.Streams/EventStoreClient.Read.cs#L353

Hope this is somewhat helpful information to you and not just a mistake on my side. If my assumption is correct then I am happy to create a Pull-Request :)

**Comment by keppelerj** [comment]
Hi @bartelink! Thanks for the quick response. I just tried running the test suite for esdb (StoreIntegration.fs is the one right?) and indeed, it fails. 
Yep looks like you are right, it's because of the TaskSeq port. Removing the wrapping of the exception fixes the issue and all tests pass :) I'll provide a PR. A new nuget release would be awesome!

**Comment by bartelink** [comment]
Excellent, thank you!
Need to go afk now; will review the PR in full later
Main thing that sticks out for now is that I'd prefer to stick with the `=  thtask {` on the previous line as per the rest of the repo - I appreciate that's non-standard, but mixing styles is even worse ;)
(If you'd prefer for me to apply style tweaks myself afterwards, rather than doing a to/fro exercise, let me know either)

**Comment by keppelerj** [comment]
Yes fully agree with you! Mixing code styles is a nightmare :D 
Do you have a "formatting/style guide" file that I can plug into my IDE by any chance? 
Changed it by hand now but usually I let my IDE format the code for me.

**Comment by bartelink** [comment]
Unfortunately the code formatting is mainly manual. There is a `.editorconfig` (which is very sparse) - open to improvements on that but in general the aim would be to have any proposed rules immediately be consistently applied, which makes it a non-trivial task. In general the `= task {` on the previous line (and closing brace on last line) is the key thing that deviates from typical conventions in the F# style guide.

Einar took a run at applying Fantomas in https://github.com/jet/equinox/pull/345 - that might be more viable had it [existed and] been used from the start - in general its rules would likely encourage pulling out more helpers etc
