### ISSUE TITLE
Is there a specific message-db version that one has to use?

### ISSUE THREAD

**Issue by keppelerj** [jet/equinox#372]
Hi, first of all - sorry if this is covered somewhere in the docs and I just couldn't find it.
I tried to use Message-db as a checkpoint store for propulsion but I'm getting the following error message:
```
System.AggregateException: One or more errors occurred. (42883: function get_stream_messages(text, bigint, bigint) does not exist

POSITION: 224)
 ---> Npgsql.PostgresException (0x80004005): 42883: function get_stream_messages(text, bigint, bigint) does not exist

POSITION: 224
   at <StartupCode$Equinox-MessageDb>.$MessageDbClient.ReadStream@106.MoveNext() in /_//src/Equinox.MessageDb/MessageDbClient.fs:line 120
   at Equinox.MessageDb.Read.readSliceAsync@174.MoveNext() in /_//src/Equinox.MessageDb/MessageDb.fs:line 175
```

When I had a look into the function signature inside the postgres I saw that the signature was actually `function get_stream_messages(varchar, bigint, bigint, varchar)` which seems to indicate that the fourth parameter is missing.

Is there a specific message-db version that one has to use in order to make it work? 
So far I tried v1.2.6 and v1.3.0.

If it helps in any way, this is the Dockerfile I used:
```FROM postgres:15.2-alpine
ARG MESSAGE_DB_VERSION

WORKDIR /usr/src
ADD https://github.com/message-db/message-db/archive/v1.3.0.tar.gz message-db.tar.gz
RUN tar -xzf message-db.tar.gz
RUN mv message-db-${MESSAGE_DB_VERSION} message-db

WORKDIR /
COPY docker-entrypoint-initdb.d /docker-entrypoint-initdb.d
```

Thanks for your help and sorry again if this is already covered somewhere!

**Comment by bartelink** [comment]
Thanks once again for taking the time to write a clear and complete issue; apologies that you're running into shortcomings...
@nordfjord what's the min and/or recommended version?
Docs: https://github.com/jet/equinox#use-messagedb
This might have the answer: https://github.com/jet/equinox/pull/360 (it goes without saying that the best way to address all of this is of course to get the integration test rig more complete; in the short to medium term, a change to the docker config that establishes the prerequisites would be useful)
Obviously, ideally a minimum schema version would be mentioned somewhere in the docs and/or be wired into the integration tests config;)

**Comment by nordfjord** [comment]
The minimum schema version is 1.3.0 as we use the nee feature of getting the last message of a particular type. This should definitely be documented! I’ll get a PR going for those docs

**Comment by nordfjord** [comment]
Are you calling the install script from your docker file? I recommend taking a look at https://gitlab.com/such-software/message-db-docker for prior art

**Comment by keppelerj** [comment]
Hey @nordfjord thanks for the advice! I briefly tried it with the Dockerfile you provided but I'm still getting the same error unfortunately. Also I didnt have much time today to check it in more detail but maybe I'm doing something entirely wrong?
To give more context: I am using ESDB on the Write-Side (which works fine by itself) and Message-db for the Checkpoint Store on the Read-Side

Basically this is the code I am using right now (Read-Side):
```
member this.Sink(log) =
        let stats = Stats(log, TimeSpan.FromMinutes 1, TimeSpan.FromMinutes 1)

        Propulsion.Streams.Default.Config.Start(
            log,
            maxReadAhead = 100,
            maxConcurrentStreams = 1,
            handle = handle,
            stats = stats,
            statsInterval = TimeSpan.FromMinutes 1
        )


override _.ExecuteAsync(ct) =
    let computation =
      async {
        use sink = service.Sink(log)
        let checkpoints =
            ReaderCheckpoint.CheckpointStore(
                "Host=localhost; Port=5432; Username=postgres; Password=changeme; Database=message_store",
                "message_store",
                "test-group",
                TimeSpan.FromSeconds 10
            )
        do! checkpoints.CreateSchemaIfNotExists() |> Async.AwaitTask
        
        use src =
          EventStoreSource(
            log,
            statsInterval = TimeSpan.FromMinutes 1,
            client = EventStoreDbProvider.client,
            batchSize = 1000,
            tailSleepInterval = TimeSpan.FromMilliseconds 100,
            checkpoints = checkpoints,
            sink = sink,
            categories = categories
          )
            .Start()
        do! src.AwaitWithStopOnCancellation()
      }

    Async.StartAsTask(computation, cancellationToken = ct)
```

which seems to run just fine (and also creates the Tables for the Checkpoint Store + first checkpoint position successfully):
```
[14:02:13 INF] Starting 1 tranche readers...
[14:02:13 INF] Reading 0 eventStoreDb/0 From 0 Checkpoint Event interval 0.2m
```
until I add an event to the EventStore:
```
     System.AggregateException: One or more errors occurred. (42883: function get_stream_messages(text, bigint, bigint) does not exist
      
      POSITION: 224)
       ---> Npgsql.PostgresException (0x80004005): 42883: function get_stream_messages(text, bigint, bigint) does not exist
      
      POSITION: 224
         at <StartupCode$Equinox-MessageDb>.$MessageDbClient.ReadStream@106.MoveNext() in /_//src/Equinox.MessageDb/MessageDbClient.fs:line 120
         at Equinox.MessageDb.Read.readSliceAsync@174.MoveNext() in /_//src/Equinox.MessageDb/MessageDb.fs:line 175

```

I hope this is somewhat helpful information.
Thanks again for your help!

**Comment by nordfjord** [comment]
Thanks for reporting, that’s really helpful. I’ll have some time to dig into this later this evening and will get back to you. This checkpoint store shouldn’t need message db in the schema at all, so that’s an interesting error indeed

**Comment by nordfjord** [comment]
Alright, I've set up a repro in this repository https://github.com/nordfjord/propulsion-repro-2023-03

I'm not able to reproduce the behaviour you're seeing. Could it be that you're trying to use a postgres role that doesn't have enough access?

**Comment by keppelerj** [comment]
Hi @nordfjord, thank you so much for your help. 
It worked for me with your repo (though I had to change the docker image bc. it didn't match my host platform `WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested`) 
Anyway I had some time to dig deeper into my code and found the error. I accidentally configured one of my services that uses the Equinox.Decider with a MessageDbCategory instead of a EventStoreCategory...🤦‍♂️.

Sorry again for the trouble.

**Comment by bartelink** [comment]
Closing (what I presume to be from scanning ☝️) a stale issue
